name: Build and Deploy

on:
  pull_request:
    types: [closed]

jobs:
  build_image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    services:
     postgres:
        image: postgres:latest
        env:
            POSTGRES_DB: testdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
        ports:
            - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Install Node.js dependencies
          run: npm install
            
        - name: Run tests
          env:  
            DB_USERNAME: postgres
            DB_PASSWORD: mypassword
            DB_NAME: testdb
            DB_HOST: 127.0.0.1
          run: npm run ghworkflowtest
          